### ISSUE TITLE
Error: Service unavailable (69)

### ISSUE THREAD

**Issue by vin-ni** [vulgo/bootoption#1]
When I `sudo bootoption order 2 to 1` I get `Error: Service unavailable (69)` Any idea what could be the issue? I also can't hide any options.

Thanks!

**Comment by vulgo** [comment]
Hi. Is SIP disabled (for unrestricted NVRAM)? EmuVariableUEFI driver should not be in use either?

**Comment by vulgo** [comment]
0.2.7 was released with [this commit](https://github.com/vulgo/bootoption/commit/8d202562e9033798bb5ac23e335c259546797aa7) which should fix set operations on existing options without optional data.

**Comment by vin-ni** [comment]
thanks!
