### ISSUE TITLE
Installation error on OSX Mojave

### ISSUE THREAD

**Issue by sanssg** [vulgo/bootoption#3]
users-iMac:~ user$ brew install bootoption
==> Installing bootoption from vulgo/repo
==> Downloading https://github.com/vulgo/bootoption/archive/v0.2.7.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/98526c425f0416d0cf441113132aea223736d12299f92e9fa23544477ef96395--bootoption-0.2.7.tar.gz
==> swift build --disable-sandbox --configuration release -Xswiftc -target -Xswi
Last 15 lines from /Users/user/Library/Logs/Homebrew/bootoption/01.swift:
2018-10-06 21:15:15 +0800

swift
build
--disable-sandbox
--configuration
release
-Xswiftc
-target
-Xswiftc
x86_64-apple-macosx10.12

error: terminated(72): xcrun --sdk macosx --find xctest output:

**Comment by vulgo** [comment]
What is the output from `xcode-select -p` or `xcrun --sdk macosx --find xctest`?

**Comment by rox97** [comment]
I have the same problem. The output is three blank rows

**Comment by rox97** [comment]
i have the same problem.
MacBook-Pro:~ user$ xcrun --sdk macosx --find xctest
xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
MacBook-Proi:~ user$ xcode-select -p
/Library/Developer/CommandLineTools

**Comment by vulgo** [comment]
Is Xcode 10 installed? Are the xcode 10 command line tools also installed? If so try selecting developer tools therein: 

```
sudo xcode-select -s /Applications/Xcode.app
```

**Comment by rox97** [comment]
it works! thank you!
